url: "https://backup158.github.io/" # the base hostname & protocol for your site
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
